//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4ISIP_520_ZiborovaUliana
{
    using System;
    using System.Collections.Generic;
    
    public partial class countr
    {
        public int ID { get; set; }
        public string Название_страны { get; set; }
        public string Английское_название { get; set; }
        public string Код { get; set; }
        public Nullable<double> Код2 { get; set; }
    }
}
