//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4ISIP_520_ZiborovaUliana
{
    using System;
    using System.Collections.Generic;
    
    public partial class meropriatia
    {
        public int id { get; set; }
        public string Событие { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> DAYS { get; set; }
        public Nullable<int> Город { get; set; }
    }
}
