//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4ISIP_520_ZiborovaUliana
{
    using System;
    using System.Collections.Generic;
    
    public partial class moderator
    {
        public int ID { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> пол { get; set; }
        public string почта { get; set; }
        public Nullable<System.DateTime> дата_рождения { get; set; }
        public Nullable<int> страна { get; set; }
        public string телефон { get; set; }
        public string направление { get; set; }
        public string мероприятие { get; set; }
        public string пароль { get; set; }
        public string фото { get; set; }
    }
}
