//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4ISIP_520_ZiborovaUliana
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uch
    {
        public Nullable<int> ID { get; set; }
        public string FIO { get; set; }
        public string Почта { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Страна { get; set; }
        public double Телефон { get; set; }
        public string Пароль { get; set; }
        public string Фото { get; set; }
        public int Пол { get; set; }
    }
}
